spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-repo/config-repo
          search-paths: test
          default-label: test

message: "This is the test profile"