server:
  port: 8080
spring:
  application:
    name: example-service
  datasource:
    url: jdbc:mysql://localhost:3306/example
    username: user
    password: password

# Development profile-specific configuration properties
logging:
  level:
    org.springframework: DEBUG
    com.example: DEBUG
