# Common configuration properties applicable to all profiles
server:
  port: 8080
spring:
  application:
    name: example-service
  datasource:
    url: jdbc:mysql://localhost:3306/exampledb
    username: user
    password: password
